%% v1.0.0
architecture-beta
    group management[Management]
    service user(server)[User] in management
    service managementServer(server)[Server] in management
    service managementStorage(disk)[Storage] in management

    junction leftManagement in management
    junction centerManagement in management
    junction rightManagement in management

    user:B -- T:leftManagement
    managementServer:B -- T:rightManagement
    leftManagement:R -- L:rightManagement
    centerManagement:L -- R:leftManagement
    centerManagement:R -- L:rightManagement
    centerManagement:B -- T:managementStorage

    group account[Account]
    service accountServer(server)[Account Server] in account
    service entryServer(server)[Entry Server] in account
    service accountStorage(disk)[Storage] in account

    junction centerAccount in account
    junction leftAccount in account
    junction rightAccount in account

    accountServer:B -- T:leftAccount
    entryServer:B -- T:rightAccount
    leftAccount:R -- L:centerAccount
    rightAccount:L -- R:centerAccount
    accountStorage:T -- B:centerAccount