%% v2.3.0
graph
    operator-runs-server --> system-run-process-that-periodically-cleanup-deleted-account
    operator-runs-server --> system-run-process-that-periodically-cleanup-expired-OTP

    operator-runs-server --> system-verified-super-user-IS-NOT-exists
    system-verified-super-user-IS-NOT-exists --> operator-input-argon2i-hashed-super-user-password
    operator-input-argon2i-hashed-super-user-password --> system-create-super-user
    system-create-super-user --> system-check-deleted-account-cleanup-time

    operator-runs-server --> system-verified-super-user-IS-exists
    system-verified-super-user-IS-exists --> system-check-deleted-account-cleanup-time
    system-check-deleted-account-cleanup-time --> system-permenently-delete-account-scheduled-to-cleanup-at-current-time

    super-user-input-password --> system-verify-super-user-credential-is-valid
    system-verify-super-user-credential-is-valid --> super-user-view-all-user
    system-verify-super-user-credential-is-valid --> super-user-delete-user
    system-verify-super-user-credential-is-valid --> super-user-create-user-by-email
    super-user-create-user-by-email --> system-store-user-email
    super-user-delete-user --> system-remove-user

    system-verify-super-user-credential-is-valid --> system-verified-OTP-mail-config-IS-NOT-set
    system-verified-OTP-mail-config-IS-NOT-set --> super-user-input-required-OTP-mail-config
    super-user-input-required-OTP-mail-config --> system-set-OTP-mail-config

    system-verify-super-user-credential-is-valid --> super-user-edit-OTP-mail-config
    super-user-edit-OTP-mail-config --> system-set-OTP-mail-config

    user-input-email --> system-generate-and-store-OTP-with-TTL
    system-generate-and-store-OTP-with-TTL --> system-send-OTP-to-user-email
    system-send-OTP-to-user-email --> user-input-OTP
    user-input-OTP --> system-verifies-user-OTP-IS-valid

    system-verifies-user-OTP-IS-valid --> user-view-all-real-account
    system-verifies-user-OTP-IS-valid --> user-view-all-logical-account

    system-verifies-user-OTP-IS-valid --> user-create-real-account-with-init-balance
    user-create-real-account-with-init-balance --> system-create-real-account
    system-create-real-account --> system-add-credit-entry-with-current-balance-to-real-account

    system-verifies-user-OTP-IS-valid --> user-choose-one-real-account
    user-choose-one-real-account --> user-delete-real-account
    user-delete-real-account --> system-sees-ALL-relation-account-current-balance-IS-zero
    user-delete-real-account --> system-sees-ANY-relation-account-current-balance-IS-NOT-zero
    system-sees-ANY-relation-account-current-balance-IS-NOT-zero --> system-rejects-real-account-deletion
    system-sees-ALL-relation-account-current-balance-IS-zero --> user-type-real-account-name
    user-type-real-account-name --> user-confirm-deletion
    user-confirm-deletion --> user-reconfirm-deletion
    user-reconfirm-deletion --> system-sees-real-account-name-confirmation-and-reconfirmation-IS-valid
    user-reconfirm-deletion --> system-sees-real-account-name-confirmation-and-reconfirmation-IS-NOT-valid
    system-sees-real-account-name-confirmation-and-reconfirmation-IS-NOT-valid --> system-rejects-real-account-deletion
    system-sees-real-account-name-confirmation-and-reconfirmation-IS-valid --> system-soft-delete-real-account
    system-sees-real-account-name-confirmation-and-reconfirmation-IS-valid --> system-soft-delete-relation-account
    system-soft-delete-real-account --> system-set-cleanup-time-one-month-after-deletion

    user-choose-one-real-account --> user-add-credit-entry-to-real-account
    user-add-credit-entry-to-real-account --> system-add-credit-entry-with-current-balance-to-real-account
    user-choose-one-real-account --> user-add-debit-entry-to-real-account
    user-add-debit-entry-to-real-account --> system-verifies-real-account-current-balance-will-not-goes-less-than-zero-after-debit
    system-verifies-real-account-current-balance-will-not-goes-less-than-zero-after-debit --> system-add-debit-entry-with-current-balance-to-real-account

    system-verifies-user-OTP-IS-valid --> user-create-logical-account-with-init-balance
    user-create-logical-account-with-init-balance --> system-create-logical-account
    system-create-logical-account --> user-WAS-NOT-inputting-init-balance-more-than-zero
    system-create-logical-account --> user-WAS-inputting-init-balance-more-than-zero
    user-WAS-inputting-init-balance-more-than-zero --> system-show-all-real-account-for-backing-the-entry

    system-verifies-user-OTP-IS-valid --> user-choose-one-logical-account

    user-choose-one-logical-account --> user-add-credit-entry-to-logical-account

    user-choose-one-logical-account --> user-add-debit-entry-to-logical-account
    user-add-debit-entry-to-logical-account --> system-show-all-real-account-for-backing-the-entry
    user-add-credit-entry-to-logical-account --> system-show-all-real-account-for-backing-the-entry

    system-show-all-real-account-for-backing-the-entry --> user-choose-one-real-account-for-backing-the-entry
    user-choose-one-real-account-for-backing-the-entry --> system-sees-relation-account-NOT-exists
    system-sees-relation-account-NOT-exists --> system-create-relation-account
    user-choose-one-real-account-for-backing-the-entry --> system-sees-relation-account-exists

    system-create-relation-account --> user-was-adding-credit-entry
    system-sees-relation-account-exists --> user-was-adding-credit-entry

    system-create-relation-account --> user-was-adding-debit-entry
    system-sees-relation-account-exists --> user-was-adding-debit-entry

    user-was-adding-credit-entry --> system-add-credit-entry-with-current-balance-to-real-account
    user-was-adding-credit-entry --> system-add-credit-entry-with-current-balance-to-logical-account
    user-was-adding-credit-entry --> system-add-credit-entry-with-current-balance-to-relation-account

    user-was-adding-debit-entry --> system-sees-relation-account-current-balance-IS-NOT-sufficient
    user-was-adding-debit-entry --> system-sees-relation-account-current-balance-IS-sufficient
    system-sees-relation-account-current-balance-IS-NOT-sufficient --> system-sees-real-account-current-balance-IS-sufficient
    system-sees-relation-account-current-balance-IS-NOT-sufficient --> system-sees-real-account-current-balance-IS-NOT-sufficient
    system-sees-real-account-current-balance-IS-sufficient --> system-add-credit-entry-with-current-balance-to-relation-account-as-much-as-the-remainder
    system-sees-real-account-current-balance-IS-sufficient --> system-add-credit-entry-with-current-balance-to-logical-account-as-much-as-the-remainder
    system-sees-real-account-current-balance-IS-NOT-sufficient --> system-rejects-the-debit-entry

    system-sees-relation-account-current-balance-IS-sufficient --> system-add-debit-entry-with-current-balance-to-real-account
    system-sees-relation-account-current-balance-IS-sufficient --> system-add-debit-entry-with-current-balance-to-relation-account
    system-sees-relation-account-current-balance-IS-sufficient --> system-add-debit-entry-with-current-balance-to-logical-account
    system-add-credit-entry-with-current-balance-to-logical-account-as-much-as-the-remainder --> system-add-debit-entry-with-current-balance-to-real-account
    system-add-credit-entry-with-current-balance-to-logical-account-as-much-as-the-remainder --> system-add-debit-entry-with-current-balance-to-relation-account
    system-add-credit-entry-with-current-balance-to-logical-account-as-much-as-the-remainder --> system-add-debit-entry-with-current-balance-to-logical-account
    system-add-credit-entry-with-current-balance-to-relation-account-as-much-as-the-remainder --> system-add-debit-entry-with-current-balance-to-real-account
    system-add-credit-entry-with-current-balance-to-relation-account-as-much-as-the-remainder --> system-add-debit-entry-with-current-balance-to-relation-account
    system-add-credit-entry-with-current-balance-to-relation-account-as-much-as-the-remainder --> system-add-debit-entry-with-current-balance-to-logical-account

    user-choose-one-logical-account --> user-choose-one-other-logical-account-to-move-balance
    user-choose-one-other-logical-account-to-move-balance --> system-show-all-relation-account-of-source-logical-account
    system-show-all-relation-account-of-source-logical-account --> user-choose-one-relation-account-of-source-logical-account
    user-choose-one-relation-account-of-source-logical-account --> system-show-all-relation-account-of-destination-logical-account
    system-show-all-relation-account-of-destination-logical-account --> user-choose-one-relation-account-of-destination-logical-account
    user-choose-one-relation-account-of-destination-logical-account --> system-sees-relation-account-of-source-and-destination-logical-account-IS-backed-by-the-same-real-account
    system-sees-relation-account-of-source-and-destination-logical-account-IS-backed-by-the-same-real-account --> system-add-debit-entry-with-current-balance-to-source-relation-account
    system-sees-relation-account-of-source-and-destination-logical-account-IS-backed-by-the-same-real-account --> system-add-debit-entry-with-current-balance-to-source-logical-account
    system-sees-relation-account-of-source-and-destination-logical-account-IS-backed-by-the-same-real-account --> system-add-credit-entry-with-current-balance-to-destination-relation-account
    system-sees-relation-account-of-source-and-destination-logical-account-IS-backed-by-the-same-real-account --> system-add-credit-entry-with-current-balance-to-destination-logical-account
    user-choose-one-relation-account-of-destination-logical-account --> system-sees-relation-account-of-source-and-destination-logical-account-IS-NOT-backed-by-the-same-real-account
    system-sees-relation-account-of-source-and-destination-logical-account-IS-NOT-backed-by-the-same-real-account --> system-add-debit-entry-with-current-balance-to-source-real-account
    system-sees-relation-account-of-source-and-destination-logical-account-IS-NOT-backed-by-the-same-real-account --> system-add-debit-entry-with-current-balance-to-source-relation-account
    system-sees-relation-account-of-source-and-destination-logical-account-IS-NOT-backed-by-the-same-real-account --> system-add-debit-entry-with-current-balance-to-source-logical-account
    system-sees-relation-account-of-source-and-destination-logical-account-IS-NOT-backed-by-the-same-real-account --> system-add-credit-entry-with-current-balance-to-destination-real-account
    system-sees-relation-account-of-source-and-destination-logical-account-IS-NOT-backed-by-the-same-real-account --> system-add-credit-entry-with-current-balance-to-destination-relation-account
    system-sees-relation-account-of-source-and-destination-logical-account-IS-NOT-backed-by-the-same-real-account --> system-add-credit-entry-with-current-balance-to-destination-logical-account