%% v2.0.0
erDiagram
    CONFIG {
        uint32 cleanUpAccountSeconds
    }

    SUPER-USER {
        string passwordHash
        string passwordSalt
        uint32 passwordTime
        uint32 passwordThreads
        uint32 passwordKeyLen
    }

    USER {
        byte(16) id
        string name
        string email
    }

    OTP {
        byte(16) id
        string nonceHex
        string otp
    }

    OTP-MAIL-CONFIG {
        string host
        string username
        string password
        string senderEmail
    }

    USER-SESSION {
        byte(16) id
        string token
        datetime issuedAt
        datetime expiredAt
    }

    REAL-ACCOUNT {
        byte(16) id
        string name
        datetime deletedAt
    }

    LOGICAL-ACCOUNT {
        byte(16) id
        string name
        datetime deletedAt
    }

    RELATION-ACCOUNT {
        byte(16) id
        string name
        datetime deletedAt
    }

    LOGICAL-ENTRY {
        byte(16) id
    }

    RELATION-ENTRY {
        byte(16) id
        datetime datetime
        string description
        int64 amount
        int64 currentBalance
    }

    REAL-ENTRY {
        byte(16) id
        datetime datetime
        string description
        int64 amount
        int64 currentBalance
    }

    USER ||--o{ OTP : ""
    OTP ||--o| USER-SESSION : ""

    LOGICAL-ACCOUNT ||--o{ RELATION-ACCOUNT: ""
    RELATION-ACCOUNT }o--|| REAL-ACCOUNT: ""

    REAL-ACCOUNT ||--o{ REAL-ENTRY : ""
    RELATION-ACCOUNT ||--o{ RELATION-ENTRY : ""
    LOGICAL-ACCOUNT ||--o{ LOGICAL-ENTRY : ""

    LOGICAL-ENTRY |o--|| RELATION-ENTRY : ""
    RELATION-ENTRY |o--|| REAL-ENTRY : ""