%% v1.0.0
graph LR
    subgraph entity
        op([operator])
        su([super-user])
        us([user])
        ac([account])
        ae([account-entry])
    end

    subgraph API
        operator-input-argon2i-hashed-super-user-password["POST /super-user/password"]
        user-input-user-code-or-super-user-input-password["POST /login"]
        super-user-create-user-code["POST /user-code"]
        super-user-delete-user-code["DELETE /user-code/{id}"]
        user-view-all-real-account["GET /account/real"]
        user-view-all-logical-account["GET /account/logical"]
        user-add-real-account["POST /account/real"]
        user-create-logical-account-with-init-balance["POST /account/logical"]
    end